apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: commafeed
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s

    objects: |
      array:
        - |
          objectName: commafeed-connection-string
          objectType: secret
        - |
          objectName: commafeed-storage-account-name
          objectType: secret
        - |
          objectName: commafeed-blob-sas
          objectType: secret
        - |
          objectName: commafeed-db-username
          objectType: secret
        - |
          objectName: commafeed-db-password
          objectType: secret

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects:
    - data:
        - key: commafeed-connection-string
          objectName: commafeed-connection-string
        - key: commafeed-storage-account-name
          objectName: commafeed-storage-account-name
        - key: commafeed-blob-sas
          objectName: commafeed-blob-sas
      secretName: azure-creds
      type: Opaque

    - data:
        - key: username
          objectName: commafeed-db-username
        - key: password
          objectName: commafeed-db-password
      secretName: commafeed-db-creds
      type: kubernetes.io/basic-auth

    - data:
        - key: CF_DATABASE_USER
          objectName: commafeed-db-username
        - key: CF_DATABASE_PASSWORD
          objectName: commafeed-db-password

      secretName: commafeed-container-env
      type: Opaque
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-cloudflare
  namespace: commafeed
spec:
  provider: azure
  parameters:
    keyvaultName: mischa-homelab-k8s
    objects: |
      array:
        - |
          objectName: commafeed-cloudflare-tunnel
          objectType: secret
    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7
