apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-v1
spec:
  # storageClassName: synology-smb-retain
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
